#服务配置
server:
  port: 9002
#spring配置
spring:
  #1.应用配置
  application:
    name: ihrm-system #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  #3.Jpa
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379

jwt:
  config:
    key: saas-ihrm
    ttl: 3600000

#微服务注册到eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/

ai:
  appId: 31274628
  apiKey: 4asXfetPimHVuSuQtbEHpQEr
  secretKey: sjKwqu43Z06UTkdPQdlsy1d3BBg81obn
  imageType: BASE64
  groupId: itcast
qr:
  url: http://127.0.0.1:8080/#/facelogin